PR : pagination관련 수정요청사항 반영해서 수정완료
mobi-projects/chaeg-check pull request #132
Opened 2024-05-20 09:53 UTC by snkchan

## 🔥 Issues

- #93 

<br/>
<br/>

## 🎯 작업 내용

- [feat : 페이지네이션 클릭시 화면 최상단으로 이동하는 goToTop 적용](https://github.com/mobi-projects/chaeg-check/commit/829fd5a4e06d50e070f376d86cae0e08d8cc5201)
## 🔧수정요청사항 : `버튼 클릭시 상단으로 화면이동기능 추가해주세요`
페이지네이션 버튼 클릭시 화면상단으로 이동해주는 기능을 추가해달라는 요청이 있었습니다.
`pagination > pagination.func.ts `에서 `goToTop()`함수를 생성하고 적용 했습니다.  
- ------------------------
- [refactor : 클릭된 버튼 색상보이도록 refactor](https://github.com/mobi-projects/chaeg-check/commit/bf888e959d5da2d55d389eb729f2280e61a25469)
## 🔧수정요청사항 : `클릭된 버튼 색상보이도록 해주세요`
공용컴포넌트 `<Button/>`은 `variant`라는 값을 입력받아 색상을 결정하도록 설계되있습니다. 이를 이용해서 
```ts
 return Array.from({ length: endNum - startNum + 1 }, (_, idx) => {
      const isClikced = page === idx + startNum ? "default" : "outline"
      return (  <Button  variant={isClikced}  >{startNum + idx} </Button>  ) 
```
클릭된 버튼은 `default색상` 나머지버튼은 색상이없는 `outline`색상을 부여받도록 했습니다.
### 결과물
![bandicam-2024-05-20-18-47-53-782](https://github.com/mobi-projects/chaeg-check/assets/144839872/98881f42-5839-4870-baf4-39f8a37f092e)

---------------
- [refactor : pagination관련 상수 별도분리](https://github.com/mobi-projects/chaeg-check/commit/3784f3a860d80253daf1c88092f0e449b31d8717)
## 이전에는
이전구조에서는 pagination폴더와 home폴더아래서 `한페이지당 불러올 책의수,전체책의수` 를 다루는 상수가 각각 존재했습니다.

## 수정후에는
결국 pagination과 관련된 상수이기때문에 이를 한파일에서 관리하도록 수정했습니다.
`const > pagination.ts`파일아래서 해당 값들을 관리하도록 변경했습니다.

## 다음작업은?
이전 작업과정에서 한파일에 모두 작업해서 관심사분리가 진행되지 않은상태라 다음 PR에 관심사분리를 진행한 내용을 올리겠습니다.
<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] Issue 번호 설정 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

-----

#### 🙏 꼭 리뷰 남겨주세요.!!
- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-05-20 16:06 UTC, TransparentDeveloper requested changes
고생하셨습니다.!

2024-05-20 16:06 UTC, TransparentDeveloper commented on src/components/index.ts
>  export * from "./pagination"
# Request Level

  - [x] "🚧 재고해주시길.."


# Description

- `dropdown` 사용 안하는 걸로 하는 건가요?? pr 본문에도 안나와 있어서;;;
- 별도의 커밋으로 분리했으면 좋았을 거 같아요.
- 지금 👇 이 pr 에 있어서,,
  - [refactor : pagination관련 상수 별도분리](https://github.com/mobi-projects/chaeg-check/pull/132/commits/3784f3a860d80253daf1c88092f0e449b31d8717)

2024-05-20 16:06 UTC, TransparentDeveloper commented on src/components/pagination/pagination.hook.ts
>  import type { ChangeUrlFT, usePaginationPorps } from "./pagination.type"
# Request Level

  - [x] "🚧 재고해주시길.."

# Description
- `usePaginationPorps` 이건 아마 초기에 선언된 타입 같은데, 컨벤션 적용해서 수정해주실 수 있나요?

2024-05-20 16:14 UTC, TransparentDeveloper requested changes

2024-05-20 16:14 UTC, TransparentDeveloper commented on src/components/pagination/pagination.hook.ts
>   * @notice
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"

# Description
- 이제 해당 부분의 내용은 다 적용된 것 같은 삭제해주셨으면 좋겠습니다.!

2024-05-20 16:14 UTC, TransparentDeveloper commented on src/components/pagination/index.tsx
> +      return (
# Request Level

  - [x] "🚧 재고해주시길.."

# Description
## 1. `const isClikced = page === idx + ...`
- 배열 순회문 안에 수식을 적는 게 잘 읽히지 않는 거 같아요.
- 상단에 함수를 분리&선언하고, 이곳에서 호출만 하는 게 좋지 않을까요??

## 2. `Array.from({ length: endNum - startNum + 1 }`
- `endNum - startNum + 1` lenght 속성에서 연산이 진행하는 것보다.

```ts
const btnLenPerPage =  endNum - startNum + 1
...
return Array.from({ length: btnLenPerPage },(_,idx)=>{...}) 
```
이렇게 하는 편이 조금더 클린하다고 저는 생각하는데 어떠신가요?

2024-05-20 16:23 UTC, snkchan commented on src/components/pagination/index.tsx
> +      return (
- @TransparentDeveloper 
-`이전 작업과정에서 한파일에 모두 작업해서 관심사분리가 진행되지 않은상태라 다음 PR에 관심사분리를 진행한 내용을 올리겠습니다.`
- 사실 이PR을열기전에 관심사 분리까지한번에 진행해서 코드작업을 마쳤었는데 `ui수정사항 반영`이라는 PR제목의 범주에 포함되지않는다고 생각해서 브랜치를 삭제하고 ui변경사항만 반영해서 PR을열었습니다.
- 관심사분리까지해서 PR을 올리려고하니 커밋만8개에 변경점이너무 많이잡히더라구요..

- 의견주신부분은 동의합니다. 추후에 올라오는 PR에 적용해서 pr을열겠습니다.

2024-05-20 16:43 UTC, snkchan commented on src/components/pagination/pagination.hook.ts
>  import type { ChangeUrlFT, usePaginationPorps } from "./pagination.type"
- 이부분은 관심사분리PR에서 진행해도될까요??? 
- 이미 작업해둔 pagination 컴포넌트 관심사분리작업에서는 요청주신부분이 적용되있습니다.!

2024-05-20 16:44 UTC, snkchan commented on src/components/pagination/pagination.hook.ts
>   * @notice
- 이부분은 관심사분리PR에서 진행해도될까요??? 
- 이미 작업해둔 pagination 컴포넌트 관심사분리작업에서는 요청주신부분이 적용되있습니다.!

2024-05-20 16:45 UTC, snkchan commented on src/components/pagination/index.tsx
>    }
- 좋은 지적감사합니다..!!👍👍
- 저는 놓치고갔던 부분인데 잘봐주셨네요... 바로 반영해서 수정완료했습니다.
- [fix : 불필요한 매개변수 수정](https://github.com/mobi-projects/chaeg-check/pull/132/commits/f41a4c9a824be10b5fabfa08e96ce4db701b9406)

2024-05-21 08:05 UTC, TransparentDeveloper commented
PR 구분이 어떻게 되어있는지 잘 모르겠습니다.

정확히 말씀드려서,, 
pr 제목 상으로 "pagination 관련~" 이렇게 설정하셨습니다.,

그런데 페이지네이션 컴포넌트 관련해서 요청드린 것에 대해, 다음 pr 에 반영하겠다는 답변이 대부분입니다..
더이상 어떤걸 리뷰해야할지 모르겠습니다..

일단 여기에 추가 리뷰를 더 남기고, merge 된 이후에 
추가 리뷰를 반영한 [페이지네이션 관련 pr] 을 한번 더 열어야 하는 상황인가요?

2024-05-21 08:50 UTC, snkchan commented on src/components/pagination/pagination.hook.ts
>   * @notice
- [fix : 불필요한 주석제거](https://github.com/mobi-projects/chaeg-check/pull/132/commits/c269eb1e7b6962da6b5f79e7e93dc7bd0fed3d96)
더이상필요없는 주석 삭제했습니다.

2024-05-21 08:52 UTC, snkchan commented on src/components/pagination/pagination.hook.ts
>  import type { ChangeUrlFT, usePaginationPorps } from "./pagination.type"
- [fix : 컨밴션에 맞는 type선언](https://github.com/mobi-projects/chaeg-check/pull/132/commits/943acbe0bb9c3d391ae4afd0f830f5ec13e95f6c)
- 초기에선언됐던 type이라 수정완료했습니다
```ts
type UsePaginationPT = {totalPageLength:number}  // 이렇게 수정했습니다.
```

2024-05-21 09:10 UTC, snkchan commented on src/components/pagination/index.tsx
> +      return (
- [feat : 클릭된 버튼 인지아닌지 반환하는 isClickedButton 선언](https://github.com/mobi-projects/chaeg-check/pull/132/commits/a43e9d1ad0882f5f9920741285b3eb4de30568ee)
```ts
 const isClickedButton: IsClickedButtonFT = ({ curPage, buttonNumber }) => { // 현재페이지, 버튼의숫자를입력받습니다.
    let result = false  
    if (curPage === buttonNumber) {
      result = true // 선택된 버튼반 true로바꿔줌
    }
    return result ? "default" : "outline" // 선택된버튼이라면 default색상 , 나머지버튼은 outline색상
  }
```
이런식으로 함수를 만들어봤는데 괜찮나요?

2024-05-21 09:11 UTC, snkchan commented on src/components/pagination/index.tsx
> +      return (
```ts
endNum - startNum + 1 lenght 속성에서 연산이 진행하는 것보다.
const btnLenPerPage =  endNum - startNum + 1
...
return Array.from({ length: btnLenPerPage },(_,idx)=>{...}) 
```

의견남겨주신것 반영해서 
```ts
 const buttonLength = endNum - startNum + 1
    return Array.from({ length: buttonLength }, (_, idx) => {

```
의 형태로 수정했습니다..

2024-05-21 09:15 UTC, snkchan commented on src/components/pagination/index.tsx
>    }
@TransparentDeveloper 
아 제가 깜빡하고 
```ts
<Button
          variant={isClikced}
          key={idx}
          id={`${idx + startNum}`} // 여기부분을 삭제하지못한채 커밋을올렸습니다....!
          onClick={(e) => {
            onClickNumBtn(e)// 
          }}
        >
          {startNum + idx}
        </Button>
```
id라는 키값을 삭제하지 않고 그대로 커밋을올린것을 지금확인해서
- [feat : 클릭된 버튼 인지아닌지 반환하는 isClickedButton 선언](https://github.com/mobi-projects/chaeg-check/pull/132/commits/a43e9d1ad0882f5f9920741285b3eb4de30568ee)
해당커밋에서 삭제를 했습니다...

2024-05-21 10:16 UTC, TransparentDeveloper requested changes
의견 반영해주셔서, 감사합니다. ^^

2024-05-21 10:16 UTC, TransparentDeveloper commented on src/components/pagination/index.tsx
> +      )
# Request Level
  - [x] "🚧 재고해주시길.."


# Description
- `idx + startNum` 이런 연산이 반복되는 것 같은데, 
```ts
const buttonNumber = idx + startNum
```
이렇게 선언해서 사용하는 편이 어떤가요??

props 넘기는 코드도 줄고, 값을 추적하는 것도 편리해질 것 같습니다:)

2024-05-21 10:16 UTC, TransparentDeveloper commented on src/components/pagination/index.tsx
>    }
# Request Level

  - [x] "🚧 재고해주시길.."

# Description
- 이 부분도 해당 pr 에서 분리할 수 있을까요??

2024-05-21 10:16 UTC, TransparentDeveloper commented on src/components/pagination/index.tsx
>    const { page, pagenationBtnLength, totalPage, changeUrl } = usePagination({
# Request Level

  - [x] "🚧 재고해주시길.."

# Description
- `pagenation` 으로 작성된 함수명/변수명 이 많이 있습니다.
- 전체적으로 `pagination` 으로 수정되었을면 좋겠습니다. 🥹

2024-05-21 10:27 UTC, snkchan commented on src/components/pagination/index.tsx
> +      )
@TransparentDeveloper 
아 아그래도
`idx+startNum` 이라는 값이 3번이반복됩니다. 그부분을 buttonNumber로 선언해서 사용하려했늗네
그렇게하기위해서는 위에 의견주신것처럼 반복문안에서 선언을해야해서 ,,, 그부분이 맞나싶어서 수정하지않았는데
아무래도 지금의견주신거처럼 `buttonNumber=idx+startNum` 으로 선언해서 사용하는편이좋겠죠?

2024-05-21 10:30 UTC, snkchan commented on src/components/pagination/index.tsx
>    }
- 지금 요청주신 부분은 제가 따로PR을열어도될까요????
- 지금 hooks, func으로분리하지 않고 저희가 초기에 작업해둔상태라 관심사분리가 이뤄지지 않은상태입니다. 
- 관심사분리에 관한작업까지 모두 마무리를 했었는데 기존의 구조와는 다르게  구조가 좀많이 바뀌게 되더라구요 
 별도의 PR에서 다루는것이 맞다고 판단이됩니다.
`ex) pagination 관심사분리 진행했습니다.`와같은 제목의 PR로 따로 다루려고 하는데 그 편이더 좋지않을까요?

2024-05-21 14:09 UTC, TransparentDeveloper commented on src/components/pagination/index.tsx
>    }
넵 알겠습니다:)

2024-05-21 18:21 UTC, snkchan commented on src/components/pagination/index.tsx
> +      )
- [feat : 중복되는 값 변수로 선언](https://github.com/mobi-projects/chaeg-check/pull/132/commits/27ffc562892acdd49cbcea4b33927d30259470c1)
- 반복문안에 `buttonNumber = idx + startNum` 으로 선언해서 수정완료했습니다.

- 혹시몰라서 
```ts
getButtonNumber() 함수를 정의해서 적용해봤는데 
```
아래와 같이 코드가 너무길어져서 반복문안에 직접 buttonNumber을 선언했는데 어떤게 더 좋을까요?

### 함수로분리
```ts
  const getButtonNumber: GetButtonNumberFT = ({ index, startNumber }) => {
    return index + startNumber
  }

  const PagiNationButtons = () => {
    const startNum =
      Math.floor((page - 1) / pagenationBtnLength) * pagenationBtnLength + 1

    const endNum = Math.min(startNum + pagenationBtnLength - 1, totalPage)

    const buttonLength = endNum - startNum + 1

    return Array.from({ length: buttonLength }, (_, idx) => {
      return (
        <Button
          variant={isClickedButton({
            buttonNumber: getButtonNumber({
              index: idx,
              startNumber: startNum,
            }),
            curPage: page,
          })}
          key={idx}
          onClick={() =>
            onClickNumBtn({
              buttonNumber: getButtonNumber({
                index: idx,
                startNumber: startNum,
              }),
            })
          }
        >
          {getButtonNumber({
            index: idx,
            startNumber: startNum,
          })}
        </Button>
      )
    })
  }
```

2024-05-22 05:20 UTC, TransparentDeveloper commented on src/components/pagination/index.tsx
> +      )
네,, chan 님 말씀대로 쉽게 읽히는 코드는 아닌 것 같습니다. 

특히, 함수 결과를 다른 함수의 인자로 넘기는 부분이 조금 걸리네요..

그냥 반복문 안에 변수 선언해서 사용하는 게 좋을 거 같아 보입니다.

2024-05-22 11:11 UTC, merged